In [1]:
import pandas as pd
import lightgbm as lgb 

In [2]:
df = pd.read_parquet('../Data/data_v6.1.parquet') 

In [3]:
df.columns

Index(['Airline Code', 'Aircraft Registration', 'Operator', 'Type Code',
       'Mode S', 'Serial Number', 'Age(years)', 'FROM', 'TO',
       'Arrival_Delayed', 'Departure_Status', 'STD_temp_scaled',
       'STD_dwpt_scaled', 'STD_rhum_scaled', 'STD_prcp_scaled',
       'STD_snow_scaled', 'STD_wdir_scaled', 'STD_wspd_scaled',
       'STD_wpgt_scaled', 'STD_pres_scaled', 'STD_tsun_scaled',
       'STD_coco_scaled', 'ATD_temp_scaled', 'ATD_dwpt_scaled',
       'ATD_rhum_scaled', 'ATD_prcp_scaled', 'ATD_snow_scaled',
       'ATD_wdir_scaled', 'ATD_wspd_scaled', 'ATD_wpgt_scaled',
       'ATD_pres_scaled', 'ATD_tsun_scaled', 'ATD_coco_scaled',
       'STA_temp_scaled', 'STA_dwpt_scaled', 'STA_rhum_scaled',
       'STA_prcp_scaled', 'STA_snow_scaled', 'STA_wdir_scaled',
       'STA_wspd_scaled', 'STA_wpgt_scaled', 'STA_pres_scaled',
       'STA_tsun_scaled', 'STA_coco_scaled', 'ATA_temp_scaled',
       'ATA_dwpt_scaled', 'ATA_rhum_scaled', 'ATA_prcp_scaled',
       'ATA_snow_scaled', 'ATA_w

In [4]:
columns_to_drop = [col for col in df.columns if col.startswith('ATA') or col.startswith('ATD') or col == 'Arrival_Delayed']
df.drop(columns=columns_to_drop, inplace=True)

In [5]:
# all columns of first row 
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None) 
df.dtypes

Airline Code                   category
Aircraft Registration          category
Operator                       category
Type Code                      category
Mode S                         category
Serial Number                  category
Age(years)                      float32
FROM                           category
TO                             category
Departure_Status               category
STD_temp_scaled                 float64
STD_dwpt_scaled                 float64
STD_rhum_scaled                 float64
STD_prcp_scaled                 float64
STD_snow_scaled                 float64
STD_wdir_scaled                 float64
STD_wspd_scaled                 float64
STD_wpgt_scaled                 float64
STD_pres_scaled                 float64
STD_tsun_scaled                 float64
STD_coco_scaled                 float64
STA_temp_scaled                 float64
STA_dwpt_scaled                 float64
STA_rhum_scaled                 float64
STA_prcp_scaled                 float64


In [16]:
df.head(5)

Airline Code Aircraft Registration          Operator Type Code  Mode S  \
0       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
1       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
2       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
3       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
4       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   

  Serial Number  Age(years) FROM   TO   Departure_Status  STD_temp_scaled  \
0        8873.0         5.0  YIN  TFU  Departure Delayed         0.605435   
1        8873.0         5.0  TFU  YIN  Departure Delayed         0.739130   
2        8873.0         5.0  URC  TFU  Departure Delayed         0.652174   
3        8873.0         5.0  TFU  URC  Departure Delayed         0.782609   
4        8873.0         5.0  ZHA  TFU  Departure Delayed         0.744565   

   STD_dwpt_scaled  STD_rhum_scaled  STD_prcp_scaled  STD_snow_scaled  \
0         0.672010             0.62              NaN              NaN   
1         0.863132             0.79              NaN              NaN   
2         0.727497             0.64              NaN              NaN   
3         0.852035             0.59              NaN              NaN   
4         0.898890             0.91              NaN              NaN   

   STD_wdir_scaled  STD_wspd_scaled  STD_wpgt_scaled  STD_pres_scaled  \
0         0.125000           0.0360              NaN         0.677922   
1         0.055556           0.0432              NaN              NaN   
2         0.530556           0.0144              NaN         0.688312   
3         0.083333           0.0576              NaN              NaN   
4         0.166667           0.0288              NaN         0.612338   

   STD_tsun_scaled  STD_coco_scaled  STA_temp_scaled  STA_dwpt_scaled  \
0              NaN              NaN         0.776596         0.861596   
1              NaN              NaN         0.613830         0.668329   
2              NaN              NaN         0.755319         0.860349   
3              NaN              NaN         0.712766         0.724439   
4              NaN             0.28         0.787234         0.862843   

   STA_rhum_scaled  STA_prcp_scaled  STA_snow_scaled  STA_wdir_scaled  \
0             0.66              NaN              NaN         1.000000   
1             0.62              NaN              NaN         0.125000   
2             0.74              NaN              NaN         1.000000   
3             0.47              NaN              NaN         0.944444   
4             0.63              NaN              NaN         0.111111   

   STA_wspd_scaled  STA_wpgt_scaled  STA_pres_scaled  STA_tsun_scaled  \
0         0.045570              NaN         0.590314              NaN   
1         0.037975              NaN         0.683246              NaN   
2         0.045570              NaN              NaN              NaN   
3         0.045570              NaN              NaN              NaN   
4         0.060759              NaN              NaN              NaN   

   STA_coco_scaled  STD_UTC_time_of_day_cosine  STD_UTC_time_of_year_cosine  \
0              NaN                    0.555570                    -0.492533   
1              NaN                    0.625923                    -0.507430   
2              NaN                   -0.087156                    -0.507430   
3              NaN                    0.675590                    -0.507430   
4              NaN                    0.999762                    -0.522178   

   STD_UTC_day_of_year  STD_UTC_week_of_year  STD_UTC_weekday  \
0                  244                    35                5   
1                  243                    35                4   
2                  243                    35                4   
3                  243                    35                4   
4                  242                    35                3   

   STD_UTC_hour_of_da

In [6]:
from sklearn.model_selection import train_test_split 

Convert float64 to float32 (Performance Optimization)

In [7]:
# Convert float64 to float32
float_cols = df.select_dtypes(include='float64').columns
df[float_cols] = df[float_cols].astype('float32')

# Convert int64 to int32
int_cols = df.select_dtypes(include='int64').columns
df[int_cols] = df[int_cols].astype('int32')

In [8]:
df.dtypes

Airline Code                   category
Aircraft Registration          category
Operator                       category
Type Code                      category
Mode S                         category
Serial Number                  category
Age(years)                      float32
FROM                           category
TO                             category
Departure_Status               category
STD_temp_scaled                 float32
STD_dwpt_scaled                 float32
STD_rhum_scaled                 float32
STD_prcp_scaled                 float32
STD_snow_scaled                 float32
STD_wdir_scaled                 float32
STD_wspd_scaled                 float32
STD_wpgt_scaled                 float32
STD_pres_scaled                 float32
STD_tsun_scaled                 float32
STD_coco_scaled                 float32
STA_temp_scaled                 float32
STA_dwpt_scaled                 float32
STA_rhum_scaled                 float32
STA_prcp_scaled                 float32


In [9]:
X = df.drop(columns = ["Departure_Status"])
y = df["Departure_Status"].astype('category').cat.codes
catFeat = X.select_dtypes(include='category').columns.tolist() 
catFeat 

['Airline Code',
 'Aircraft Registration',
 'Operator',
 'Type Code',
 'Mode S',
 'Serial Number',
 'FROM',
 'TO']

In [10]:
# 60 % training, 40 % temp (to split into test and validation)  
xTrain, xTemp, yTrain , yTemp = train_test_split(X, y, test_size = 0.4, random_state = 42) 

# 20 % test, 20 % validation 
xTest, xVal, yTest, yVal = train_test_split(xTemp, yTemp, test_size = 0.5, random_state = 42) 

xTrain.shape, xTest.shape, xVal.shape

((7001872, 43), (2333957, 43), (2333958, 43))

In [11]:
trainData = lgb.Dataset(data = xTrain, label = yTrain, categorical_feature = catFeat)
validData = lgb.Dataset(data = xVal, label = yVal, categorical_feature = catFeat)  

Training Starts Here

Manual Override

In [12]:
params = {
    'objective': 'multiclass',         # Binary classification
    'num_class':3,
    'metric': 'multi_logloss',    # Log loss for binary classification
    'boosting_type': 'gbdt',
    'num_leaves': 255,
    'learning_rate': 0.05,
    'verbose': -1,
}

# Training the model
model = lgb.train(
    params, 
    trainData, 
    valid_sets=[validData],
    num_boost_round=500,
    callbacks=[
        lgb.early_stopping(stopping_rounds=60),
        lgb.log_evaluation(period=10) ],
    )

Training until validation scores don't improve for 60 rounds
[10]	valid_0's multi_logloss: 0.252565
[20]	valid_0's multi_logloss: 0.235933
[30]	valid_0's multi_logloss: 0.227893
[40]	valid_0's multi_logloss: 0.223344
[50]	valid_0's multi_logloss: 0.220227
[60]	valid_0's multi_logloss: 0.217442
[70]	valid_0's multi_logloss: 0.214971
[80]	valid_0's multi_logloss: 0.213391
[90]	valid_0's multi_logloss: 0.211869
[100]	valid_0's multi_logloss: 0.211171
[110]	valid_0's multi_logloss: 0.210236
[120]	valid_0's multi_logloss: 0.209799
[130]	valid_0's multi_logloss: 0.209446
[140]	valid_0's multi_logloss: 0.209205
[150]	valid_0's multi_logloss: 0.208999
[160]	valid_0's multi_logloss: 0.20885
[170]	valid_0's multi_logloss: 0.208683
[180]	valid_0's multi_logloss: 0.208553
[190]	valid_0's multi_logloss: 0.208385
[200]	valid_0's multi_logloss: 0.208212
[210]	valid_0's multi_logloss: 0.207999
[220]	valid_0's multi_logloss: 0.207816
[230]	valid_0's multi_logloss: 0.207737
[240]	valid_0's multi_logloss

Process Flow - No eta

In [18]:
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# Define the base LightGBM model (renamed to best_model)
best_model = lgb.LGBMClassifier(
    objective='multiclass', 
    metric='multi_logloss', 
    boosting_type='gbdt',
    verbose=-1,
    random_state=42
)

# Define the hyperparameter grid based on your updated ranges
param_grid = {
    'num_leaves': [15],  # Adjusted range
    'learning_rate': [0.1],  # Adjusted range
    'n_estimators': [10,20]  # Adjusted range
}

# Initialize GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(
    estimator=best_model,  # Using best_model as the estimator
    param_grid=param_grid,
    scoring='accuracy',  
    cv=5,  # K = 5
    verbose=1,
    n_jobs=-1
)

# Train using GridSearchCV
grid_search.fit(xTrain, yTrain)

# Print the best parameters
print("Best Parameters:", grid_search.best_params_)

# Train the final model with best parameters on full training data
best_params = grid_search.best_params_

# Convert to the LightGBM Dataset format
train_data = lgb.Dataset(xTrain, label=yTrain)
valid_data = lgb.Dataset(xVal, label=yVal, reference=train_data)

# Use lgb.train for better control and early stopping (renamed to model)
model = lgb.train(
    {**best_params, "objective": "multiclass", "metric": "multi_logloss", "num_class": 3},
    train_data,
    valid_sets=[valid_data],
    num_boost_round=best_params['n_estimators'],  # Use best n_estimators from grid search
    callbacks=[
        lgb.early_stopping(stopping_rounds=60),  # Correct way to apply early stopping
        lgb.log_evaluation(period=100)  # Correct way to enable verbose logging
    ]
)

# Predict on validation set
y_pred = model.predict(xVal)

# Evaluate performance
y_pred_classes = y_pred.argmax(axis=1)

# Evaluate performance
print(f"Validation Accuracy: {accuracy_score(yVal, y_pred_classes):.4f}")

# Save the trained LightGBM model (renamed to model)
model.save_model("trial_data_model.txt")

Fitting 5 folds for each of 2 candidates, totalling 10 fits
Best Parameters: {'learning_rate': 0.1, 'n_estimators': 20, 'num_leaves': 15}
Training until validation scores don't improve for 60 rounds
Did not meet early stopping. Best iteration is:
[20]	valid_0's multi_logloss: 0.246178
Validation Accuracy: 0.9137


Process Flow - With ETA

In [36]:
import time
import lightgbm as lgb
from sklearn.model_selection import ParameterGrid, GridSearchCV
from sklearn.metrics import accuracy_score
from tqdm import tqdm  # progress bar

# Define the base LightGBM model
best_model = lgb.LGBMClassifier(
    objective='multiclass', 
    metric='multi_logloss', 
    boosting_type='gbdt',
    verbose=-1,
    random_state=42
)

# Define the hyperparameter grid
param_grid = {
    'num_leaves': [15],  # Adjusted range
    'learning_rate': [0.1],  # Adjusted range
    'n_estimators': [10,20]  # Adjusted range
}

# Generate all parameter combinations from the grid
param_combinations = list(ParameterGrid(param_grid))
progress_bar = tqdm(param_combinations, desc="Grid Search", unit="combo", ncols=100)

# Dictionary to store timing for each candidate
timing_results = {}

# Start the clock for ETA calculation
start_time = time.time()

# Iterate manually over each parameter combination and time each candidate
for i, params in enumerate(progress_bar):
    start_candidate = time.time()
    
    # Create and train a candidate model with current parameters
    candidate_model = lgb.LGBMClassifier(
        **params, 
        objective='multiclass', 
        metric='multi_logloss', 
        random_state=42
    )
    candidate_model.fit(xTrain, yTrain)
    
    candidate_time = time.time() - start_candidate
    timing_results[str(params)] = candidate_time
    
    # Calculate iterations per second (it/s)
    it_per_sec = 1.0 / candidate_time if candidate_time > 0 else float('inf')
    
    # Update the progress bar with the elapsed time and it/s
    elapsed_time = time.time() - start_time
    total_combinations = len(param_combinations)
    remaining_combinations = total_combinations - (i + 1)
    
    # Estimate remaining time (ETA)
    avg_time_per_fit = elapsed_time / (i + 1) if (i + 1) > 0 else 0
    eta = avg_time_per_fit * remaining_combinations
    eta_str = time.strftime("%H:%M:%S", time.gmtime(eta))  # Format ETA

    # Update the tqdm progress bar with the elapsed time, ETA, and it/s
    progress_bar.set_postfix({
        "elapsed_time": f"{elapsed_time:.2f}s",
        "eta": eta_str,
        "it/s": f"{it_per_sec:.2f}"
    })

# Now run GridSearchCV (this will run in parallel as specified by n_jobs)
start_grid = time.time()
grid_search = GridSearchCV(
    estimator=best_model,
    param_grid=param_grid,
    scoring='accuracy',  
    cv=5,
    verbose=1,
    n_jobs=-1
)
grid_search.fit(xTrain, yTrain)
grid_time = time.time() - start_grid
print(f"\nTotal Grid Search Time: {grid_time:.2f} seconds")

# Print timing for each candidate
print("\nTime Taken for Each Candidate:")
for param_str, t in timing_results.items():
    print(f"{param_str} -> {t:.2f} sec (it/s: {1/t if t > 0 else float('inf'):.2f})")

# Retrieve best parameters from grid search
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# Convert to the LightGBM Dataset format
train_data = lgb.Dataset(xTrain, label=yTrain)
valid_data = lgb.Dataset(xVal, label=yVal, reference=train_data)

# Train the final model using lgb.train with early stopping callbacks
model = lgb.train(
    {**best_params, "objective": "multiclass", "metric": "multi_logloss", "num_class": 3},
    train_data,
    valid_sets=[valid_data],
    num_boost_round=best_params['n_estimators'],  # using best n_estimators from grid search
    callbacks=[
        lgb.early_stopping(stopping_rounds=60),
        lgb.log_evaluation(period=100)
    ]
)

# Predict on validation set
y_pred = model.predict(xVal)
y_pred_classes = y_pred.argmax(axis=1)
val_accuracy = accuracy_score(yVal, y_pred_classes)
print(f"Validation Accuracy: {val_accuracy:.4f}")

# Save the final model
model.save_model("trial_data_model.txt")

Grid Search: 100%|███| 2/2 [00:15<00:00,  7.99s/combo, elapsed_time=15.98s, eta=00:00:00, it/s=0.10]


Fitting 5 folds for each of 2 candidates, totalling 10 fits

Total Grid Search Time: 76.22 seconds

Time Taken for Each Candidate:
{'learning_rate': 0.1, 'n_estimators': 10, 'num_leaves': 15} -> 6.11 sec (it/s: 0.16)
{'learning_rate': 0.1, 'n_estimators': 20, 'num_leaves': 15} -> 9.87 sec (it/s: 0.10)
Best Parameters: {'learning_rate': 0.1, 'n_estimators': 20, 'num_leaves': 15}
Training until validation scores don't improve for 60 rounds
Did not meet early stopping. Best iteration is:
[20]	valid_0's multi_logloss: 0.246178
Validation Accuracy: 0.9137


Validate the model on the Validation Set

In [19]:
import numpy as np
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

# Predict probabilities on the validation set
yValidatePredProbability = model.predict(xVal)  # Shape: [n_samples, n_classes]

# Convert probabilities to predicted class labels
yValidatePred = np.argmax(yValidatePredProbability, axis=1)  # Shape: [n_samples]

# Accuracy
validationAccuracy = accuracy_score(yVal, yValidatePred)
print("Validation Accuracy: ", validationAccuracy)

# AUC (for multi-class)
validationAUC = roc_auc_score(yVal, yValidatePredProbability, multi_class='ovr', average='macro')
print("Validation AUC: ", validationAUC)

# Confusion Matrix
confusionMatrix = confusion_matrix(yVal, yValidatePred)
print("Confusion Matrix: \n", confusionMatrix)

# Classification Report
classificationReport = classification_report(yVal, yValidatePred)
print("Classification Report: \n", classificationReport)

Validation Accuracy:  0.9136646846258587
Validation AUC:  0.8787325505816875
Confusion Matrix: 
 [[   8190    2060      62]
 [     48 2122131     565]
 [    259  198509    2134]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.79      0.87     10312
           1       0.91      1.00      0.95   2122744
           2       0.77      0.01      0.02    200902

    accuracy                           0.91   2333958
   macro avg       0.88      0.60      0.62   2333958
weighted avg       0.90      0.91      0.87   2333958



Test on Test Data

In [20]:
yTestPredProbability = model.predict(xTest)  # Shape: [n_samples, n_classes]

# Convert probabilities to predicted class labels
yTestPred = np.argmax(yTestPredProbability, axis=1)  # Shape: [n_samples]

# Accuracy
testAccuracy = accuracy_score(yTest, yTestPred)
print("Test Accuracy: ", testAccuracy)

# AUC (for multi-class)
testAUC = roc_auc_score(yTest, yTestPredProbability, multi_class='ovr', average='macro')
print("Test AUC: ", testAUC)

# Confusion Matrix
testConfusionMatrix = confusion_matrix(yTest, yTestPred)
print("Test Confusion Matrix: \n", testConfusionMatrix)

# Classification Report
testClassificationReport = classification_report(yTest, yTestPred)
print("Test Classification Report: \n", testClassificationReport)

Test Accuracy:  0.9135823839085296
Test AUC:  0.8784289824792889
Test Confusion Matrix: 
 [[   8239    2067      49]
 [     41 2121875     531]
 [    267  198740    2148]]
Test Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.80      0.87     10355
           1       0.91      1.00      0.95   2122447
           2       0.79      0.01      0.02    201155

    accuracy                           0.91   2333957
   macro avg       0.89      0.60      0.62   2333957
weighted avg       0.90      0.91      0.87   2333957



## Feature Importance Summary

In [21]:
import plotly.express as px
import pandas as pd

# Get Feature Importance
importance = model.feature_importance(importance_type='gain')
feature_names = X.columns

# Create DataFrame
importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importance})

# Sort by Importance (Descending)
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Plot using Plotly
fig = px.bar(
    importance_df,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Feature Importance',
    labels={'Importance': 'Gain'},
    height=600
)

# Show interactive plot
fig.show()

## Top 20 Feature Importance

In [22]:
import plotly.express as px
import pandas as pd
import numpy as np

# Get Feature Importance
importance = model.feature_importance(importance_type='gain')
feature_names = X.columns

# Get indices of top 20 most important features
top_n = 20
sorted_indices = np.argsort(importance)[-top_n:]  # Get indices of top 20 features

# Sort features and importance scores by importance
top_feature_names = np.array(feature_names)[sorted_indices]
top_importance_scores = np.array(importance)[sorted_indices]

# Create DataFrame
importance_df = pd.DataFrame({
    'Feature': top_feature_names,
    'Importance': top_importance_scores
})

# Sort by Importance (Descending)
importance_df = importance_df.sort_values(by='Importance', ascending=True)

# Plot using Plotly
fig = px.bar(
    importance_df,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Top 20 Feature Importance',
    labels={'Importance': 'Gain'},
    height=600
)

# Customize layout
fig.update_traces(marker_color='skyblue')
fig.update_layout(xaxis_gridcolor='lightgray', xaxis_gridwidth=0.5)

# Show interactive plot
fig.show()

## Predicting

In [ ]:
# Predicting on the dataset
X = df.drop(columns=["Departure_Status"])
y = df["Departure_Status"].astype('category').cat.codes
catFeat = X.select_dtypes(include='category').columns.tolist()

# Ensure categorical features are treated correctly
for col in catFeat:
    X[col] = X[col].astype('category')

# Make predictions
y_pred = model.predict(X)

# Convert probabilities to class labels
y_pred_labels = y_pred.argmax(axis=1)  # Takes the index of the max probability class

# Add predictions to the dataframe
df["Predicted_Departure_Status"] = y_pred_labels

In [ ]:
# Count occurrences of each unique value in the "Predicted_Departure_Status" column
unique_value_counts = df["Predicted_Departure_Status"].value_counts()

# Display the result
print(unique_value_counts)
## 1 Departure Delayed
## 2 Departure On Time
## 3 Cancelled


Predicted_Departure_Status
1    11479658
2      147484
0       42645
Name: count, dtype: int64


In [ ]:
unique_value_counts = df["Departure_Status"].value_counts()
print(unique_value_counts)


Departure_Status
Departure Delayed    10611222
Departure On Time     1006930
Cancelled               51635
Name: count, dtype: int64


In [ ]:
df = pd.read_parquet("../data.parquet")
df["Predicted_Departure_Status"] = y_pred_labels
output_file_path = "updated_file.parquet"  
df.to_parquet(output_file_path, index=False)

In [ ]:
import pandas as pd
df=pd.read_parquet("updated_file.parquet")
df.columns
print(len(df.columns))

68


In [ ]:
df=pd.read_parquet("../data.parquet")
df.columns
print(len(df.columns))

67
