In [2]:
import pandas as pd
import lightgbm as lgb 

In [3]:
df = pd.read_parquet('../Data/data_v6.1.parquet') 

In [4]:
df.columns

Index(['Airline Code', 'Aircraft Registration', 'Operator', 'Type Code',
       'Mode S', 'Serial Number', 'Age(years)', 'FROM', 'TO',
       'Arrival_Delayed', 'Departure_Status', 'STD_temp_scaled',
       'STD_dwpt_scaled', 'STD_rhum_scaled', 'STD_prcp_scaled',
       'STD_snow_scaled', 'STD_wdir_scaled', 'STD_wspd_scaled',
       'STD_wpgt_scaled', 'STD_pres_scaled', 'STD_tsun_scaled',
       'STD_coco_scaled', 'ATD_temp_scaled', 'ATD_dwpt_scaled',
       'ATD_rhum_scaled', 'ATD_prcp_scaled', 'ATD_snow_scaled',
       'ATD_wdir_scaled', 'ATD_wspd_scaled', 'ATD_wpgt_scaled',
       'ATD_pres_scaled', 'ATD_tsun_scaled', 'ATD_coco_scaled',
       'STA_temp_scaled', 'STA_dwpt_scaled', 'STA_rhum_scaled',
       'STA_prcp_scaled', 'STA_snow_scaled', 'STA_wdir_scaled',
       'STA_wspd_scaled', 'STA_wpgt_scaled', 'STA_pres_scaled',
       'STA_tsun_scaled', 'STA_coco_scaled', 'ATA_temp_scaled',
       'ATA_dwpt_scaled', 'ATA_rhum_scaled', 'ATA_prcp_scaled',
       'ATA_snow_scaled', 'ATA_w

In [5]:
columns_to_drop = [col for col in df.columns if col.startswith('ATA') or col.startswith('ATD') or col == 'Arrival_Delayed']
df.drop(columns=columns_to_drop, inplace=True)

In [15]:
# all columns of first row 
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None) 
df.dtypes

Airline Code                   category
Aircraft Registration          category
Operator                       category
Type Code                      category
Mode S                         category
Serial Number                  category
Age(years)                      float32
FROM                           category
TO                             category
Departure_Status               category
STD_temp_scaled                 float64
STD_dwpt_scaled                 float64
STD_rhum_scaled                 float64
STD_prcp_scaled                 float64
STD_snow_scaled                 float64
STD_wdir_scaled                 float64
STD_wspd_scaled                 float64
STD_wpgt_scaled                 float64
STD_pres_scaled                 float64
STD_tsun_scaled                 float64
STD_coco_scaled                 float64
STA_temp_scaled                 float64
STA_dwpt_scaled                 float64
STA_rhum_scaled                 float64
STA_prcp_scaled                 float64


In [16]:
df.head(5)

Airline Code Aircraft Registration          Operator Type Code  Mode S  \
0       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
1       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
2       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
3       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   
4       3u-csc                b-30cr  Sichuan Airlines      A20N  781848   

  Serial Number  Age(years) FROM   TO   Departure_Status  STD_temp_scaled  \
0        8873.0         5.0  YIN  TFU  Departure Delayed         0.605435   
1        8873.0         5.0  TFU  YIN  Departure Delayed         0.739130   
2        8873.0         5.0  URC  TFU  Departure Delayed         0.652174   
3        8873.0         5.0  TFU  URC  Departure Delayed         0.782609   
4        8873.0         5.0  ZHA  TFU  Departure Delayed         0.744565   

   STD_dwpt_scaled  STD_rhum_scaled  STD_prcp_scaled  STD_snow_scaled  \
0         0.672010             0.62              NaN              NaN   
1         0.863132             0.79              NaN              NaN   
2         0.727497             0.64              NaN              NaN   
3         0.852035             0.59              NaN              NaN   
4         0.898890             0.91              NaN              NaN   

   STD_wdir_scaled  STD_wspd_scaled  STD_wpgt_scaled  STD_pres_scaled  \
0         0.125000           0.0360              NaN         0.677922   
1         0.055556           0.0432              NaN              NaN   
2         0.530556           0.0144              NaN         0.688312   
3         0.083333           0.0576              NaN              NaN   
4         0.166667           0.0288              NaN         0.612338   

   STD_tsun_scaled  STD_coco_scaled  STA_temp_scaled  STA_dwpt_scaled  \
0              NaN              NaN         0.776596         0.861596   
1              NaN              NaN         0.613830         0.668329   
2              NaN              NaN         0.755319         0.860349   
3              NaN              NaN         0.712766         0.724439   
4              NaN             0.28         0.787234         0.862843   

   STA_rhum_scaled  STA_prcp_scaled  STA_snow_scaled  STA_wdir_scaled  \
0             0.66              NaN              NaN         1.000000   
1             0.62              NaN              NaN         0.125000   
2             0.74              NaN              NaN         1.000000   
3             0.47              NaN              NaN         0.944444   
4             0.63              NaN              NaN         0.111111   

   STA_wspd_scaled  STA_wpgt_scaled  STA_pres_scaled  STA_tsun_scaled  \
0         0.045570              NaN         0.590314              NaN   
1         0.037975              NaN         0.683246              NaN   
2         0.045570              NaN              NaN              NaN   
3         0.045570              NaN              NaN              NaN   
4         0.060759              NaN              NaN              NaN   

   STA_coco_scaled  STD_UTC_time_of_day_cosine  STD_UTC_time_of_year_cosine  \
0              NaN                    0.555570                    -0.492533   
1              NaN                    0.625923                    -0.507430   
2              NaN                   -0.087156                    -0.507430   
3              NaN                    0.675590                    -0.507430   
4              NaN                    0.999762                    -0.522178   

   STD_UTC_day_of_year  STD_UTC_week_of_year  STD_UTC_weekday  \
0                  244                    35                5   
1                  243                    35                4   
2                  243                    35                4   
3                  243                    35                4   
4                  242                    35                3   

   STD_UTC_hour_of_da

In [6]:
from sklearn.model_selection import train_test_split 

Convert float64 to float32 (Performance Optimization)

In [7]:
# Convert float64 to float32
float_cols = df.select_dtypes(include='float64').columns
df[float_cols] = df[float_cols].astype('float32')

# Convert int64 to int32
int_cols = df.select_dtypes(include='int64').columns
df[int_cols] = df[int_cols].astype('int32')

In [8]:
df.dtypes

Airline Code                   category
Aircraft Registration          category
Operator                       category
Type Code                      category
Mode S                         category
Serial Number                  category
Age(years)                      float32
FROM                           category
TO                             category
Departure_Status               category
STD_temp_scaled                 float32
STD_dwpt_scaled                 float32
STD_rhum_scaled                 float32
STD_prcp_scaled                 float32
STD_snow_scaled                 float32
STD_wdir_scaled                 float32
STD_wspd_scaled                 float32
STD_wpgt_scaled                 float32
STD_pres_scaled                 float32
STD_tsun_scaled                 float32
STD_coco_scaled                 float32
STA_temp_scaled                 float32
STA_dwpt_scaled                 float32
STA_rhum_scaled                 float32
STA_prcp_scaled                 float32


In [9]:
X = df.drop(columns = ["Departure_Status"])
y = df["Departure_Status"].astype('category').cat.codes
catFeat = X.select_dtypes(include='category').columns.tolist() 
catFeat 

['Airline Code',
 'Aircraft Registration',
 'Operator',
 'Type Code',
 'Mode S',
 'Serial Number',
 'FROM',
 'TO']

In [10]:
# 60 % training, 40 % temp (to split into test and validation)  
xTrain, xTemp, yTrain , yTemp = train_test_split(X, y, test_size = 0.4, random_state = 42) 

# 20 % test, 20 % validation 
xTest, xVal, yTest, yVal = train_test_split(xTemp, yTemp, test_size = 0.5, random_state = 42) 

xTrain.shape, xTest.shape, xVal.shape

((7001872, 43), (2333957, 43), (2333958, 43))

In [11]:
trainData = lgb.Dataset(data = xTrain, label = yTrain, categorical_feature = catFeat)
validData = lgb.Dataset(data = xVal, label = yVal, categorical_feature = catFeat)  

Training Starts Here

In [24]:
import time
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# Timer callback to log estimated remaining time for GridSearchCV
class TimerGridSearchCallback:
    def __init__(self, total_combinations):
        self.start_time = time.time()
        self.total_combinations = total_combinations
        self.completed_combinations = 0

    def __call__(self):
        elapsed_time = time.time() - self.start_time
        avg_time_per_combination = elapsed_time / self.completed_combinations if self.completed_combinations > 0 else 0
        remaining_combinations = self.total_combinations - self.completed_combinations
        remaining_time = avg_time_per_combination * remaining_combinations

        print(f"Completed {self.completed_combinations}/{self.total_combinations} combinations, "
              f"Elapsed Time: {elapsed_time:.2f}s, Estimated Remaining Time: {remaining_time:.2f}s")

    def increment(self):
        self.completed_combinations += 1
        self.__call__()

class TimerCallback:
    def __init__(self):
        self.start_time = time.time()

    def __call__(self, env):
        elapsed_time = time.time() - self.start_time
        total_rounds = env.iteration + 1
        remaining_rounds = env.params['num_boost_round'] - total_rounds
        # Estimate time remaining
        avg_time_per_round = elapsed_time / total_rounds
        remaining_time = avg_time_per_round * remaining_rounds
        print(f"Iteration {total_rounds}/{env.params['num_boost_round']}, "
              f"Elapsed Time: {elapsed_time:.2f}s, Estimated Remaining Time: {remaining_time:.2f}s")

# Define the base LightGBM model (renamed to best_model)
best_model = lgb.LGBMClassifier(
    objective='multiclass', 
    metric='multi_logloss', 
    boosting_type='gbdt',
    verbose=-1,
    random_state=42,
    num_class=3  # Specify the number of classes for multiclass classification
)

# Define the hyperparameter grid based on your updated ranges
param_grid = {
    'num_leaves': [15, 31, 63, 127, 255],  # Adjusted range
    'learning_rate': [0.01, 0.05, 0.1],  # Adjusted range
    'n_estimators': [100, 300, 500, 750, 1000]  # Adjusted range
}

# Total combinations for GridSearchCV
total_combinations = len(param_grid['num_leaves']) * len(param_grid['learning_rate']) * len(param_grid['n_estimators'])

# Initialize GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(
    estimator=best_model,  # Using best_model as the estimator
    param_grid=param_grid,
    scoring='accuracy',  
    cv=5,  # K = 5
    verbose=1,
    n_jobs=-1
)

# Create the timer callback for GridSearchCV
timer_callback = TimerGridSearchCallback(total_combinations)

# Custom fit function to increment progress and log remaining time
class GridSearchCVWithTimeLogging(GridSearchCV):
    def _run_search(self, evaluate_candidates):
        # Log the progress of GridSearchCV
        for i, params in enumerate(self.param_grid):
            timer_callback.increment()
            print(f"Running {i+1}/{total_combinations} of the parameter grid.")
        super()._run_search(evaluate_candidates)

# Initialize custom GridSearchCV with the timer
grid_search = GridSearchCVWithTimeLogging(
    estimator=best_model,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    verbose=1,
    n_jobs=-1
)

# Train using GridSearchCV and log time
grid_search.fit(xTrain, yTrain)

# Print the best parameters
print("Best Parameters:", grid_search.best_params_)

# Train the final model with best parameters on full training data
best_params = grid_search.best_params_

# Convert to the LightGBM Dataset format
train_data = lgb.Dataset(xTrain, label=yTrain)
valid_data = lgb.Dataset(xVal, label=yVal, reference=train_data)



Completed 1/75 combinations, Elapsed Time: 0.08s, Estimated Remaining Time: 6.18s
Running 1/75 of the parameter grid.
Completed 2/75 combinations, Elapsed Time: 0.08s, Estimated Remaining Time: 3.05s
Running 2/75 of the parameter grid.
Completed 3/75 combinations, Elapsed Time: 0.08s, Estimated Remaining Time: 2.01s
Running 3/75 of the parameter grid.
Fitting 5 folds for each of 75 candidates, totalling 375 fits


/Users/marcusfoo/Documents/GitHub/INF2008MachineLearning/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best Parameters: {'learning_rate': 0.05, 'n_estimators': 500, 'num_leaves': 255}


TypeError: train() got an unexpected keyword argument 'early_stopping_rounds'

In [28]:
# Use lgb.train for better control and early stopping (renamed to model)
model = lgb.train(
    {**best_params, "objective": "multiclass", "metric": "multi_logloss", "num_class": 3},
    train_data,
    valid_sets=[valid_data],
    num_boost_round=10000,
    callbacks=[lgb.early_stopping(60)]  # Correct way to enable early stopping
)

# Predict on validation set
y_pred = model.predict(xVal)

# Evaluate performance
y_pred_classes = y_pred.argmax(axis=1)
print(f"Validation Accuracy: {accuracy_score(yVal, y_pred_classes):.4f}")

# Save the trained model
model.save_model("best_grid_search_lightgbm_model.txt")

Training until validation scores don't improve for 60 rounds
Early stopping, best iteration is:
[347]	valid_0's multi_logloss: 0.207146
Validation Accuracy: 0.9226


Manual Override

In [12]:
params = {
    'objective': 'multiclass',         # Binary classification
    'num_class':3,
    'metric': 'multi_logloss',    # Log loss for binary classification
    'boosting_type': 'gbdt',
    'num_leaves': 255,
    'learning_rate': 0.05,
    'verbose': -1,
}

# Training the model
model = lgb.train(
    params, 
    trainData, 
    valid_sets=[validData],
    num_boost_round=500,
    callbacks=[
        lgb.early_stopping(stopping_rounds=60),
        lgb.log_evaluation(period=10) ],
    )

Training until validation scores don't improve for 60 rounds
[10]	valid_0's multi_logloss: 0.252565
[20]	valid_0's multi_logloss: 0.235933
[30]	valid_0's multi_logloss: 0.227893
[40]	valid_0's multi_logloss: 0.223344
[50]	valid_0's multi_logloss: 0.220227
[60]	valid_0's multi_logloss: 0.217442
[70]	valid_0's multi_logloss: 0.214971
[80]	valid_0's multi_logloss: 0.213391
[90]	valid_0's multi_logloss: 0.211869
[100]	valid_0's multi_logloss: 0.211171
[110]	valid_0's multi_logloss: 0.210236
[120]	valid_0's multi_logloss: 0.209799
[130]	valid_0's multi_logloss: 0.209446
[140]	valid_0's multi_logloss: 0.209205
[150]	valid_0's multi_logloss: 0.208999
[160]	valid_0's multi_logloss: 0.20885
[170]	valid_0's multi_logloss: 0.208683
[180]	valid_0's multi_logloss: 0.208553
[190]	valid_0's multi_logloss: 0.208385
[200]	valid_0's multi_logloss: 0.208212
[210]	valid_0's multi_logloss: 0.207999
[220]	valid_0's multi_logloss: 0.207816
[230]	valid_0's multi_logloss: 0.207737
[240]	valid_0's multi_logloss

No logging - For Binary Class

In [ ]:
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# Define the base LightGBM model (renamed to best_model)
best_model = lgb.LGBMClassifier(
    objective='binary', 
    metric='binary_logloss', 
    boosting_type='gbdt',
    verbose=-1,
    random_state=42
)

# Define the hyperparameter grid based on your updated ranges
param_grid = {
    'num_leaves': [15, 31, 63, 127, 255],  # Adjusted range
    'learning_rate': [0.01, 0.05, 0.1],  # Adjusted range
    'n_estimators': [100, 300, 500, 750, 1000]  # Adjusted range
}

# Initialize GridSearchCV with 5-fold cross-validation
grid_search = GridSearchCV(
    estimator=best_model,  # Using best_model as the estimator
    param_grid=param_grid,
    scoring='accuracy',  
    cv=5,  # K = 5
    verbose=1,
    n_jobs=-1
)

# Train using GridSearchCV
grid_search.fit(xTrain, yTrain)

# Print the best parameters
print("Best Parameters:", grid_search.best_params_)

# Train the final model with best parameters on full training data
best_params = grid_search.best_params_

# Convert to the LightGBM Dataset format
train_data = lgb.Dataset(xTrain, label=yTrain)
valid_data = lgb.Dataset(xVal, label=yVal, reference=train_data)

# Use lgb.train for better control and early stopping (renamed to model)
model = lgb.train(
    {**best_params, "objective": "binary", "metric": "binary_logloss"},  
    train_data,
    valid_sets=[valid_data],
    num_boost_round=best_params['n_estimators'],  # Use best n_estimators from grid search
    callbacks=[
        lgb.early_stopping(stopping_rounds=60),  # Correct way to apply early stopping
        lgb.log_evaluation(period=100)  # Correct way to enable verbose logging
    ]
)

# Predict on validation set
y_pred = model.predict(xVal)

# Evaluate performance
print(f"Validation Accuracy: {accuracy_score(yVal, y_pred > 0.5):.4f}")

# Save the trained LightGBM model (renamed to model)
model.save_model("best_grid_search_lightgbm_model.txt")

Validate the model on the Validation Set

In [29]:
import numpy as np
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

# Predict probabilities on the validation set
yValidatePredProbability = model.predict(xVal)  # Shape: [n_samples, n_classes]

# Convert probabilities to predicted class labels
yValidatePred = np.argmax(yValidatePredProbability, axis=1)  # Shape: [n_samples]

# Accuracy
validationAccuracy = accuracy_score(yVal, yValidatePred)
print("Validation Accuracy: ", validationAccuracy)

# AUC (for multi-class)
validationAUC = roc_auc_score(yVal, yValidatePredProbability, multi_class='ovr', average='macro')
print("Validation AUC: ", validationAUC)

# Confusion Matrix
confusionMatrix = confusion_matrix(yVal, yValidatePred)
print("Confusion Matrix: \n", confusionMatrix)

# Classification Report
classificationReport = classification_report(yVal, yValidatePred)
print("Classification Report: \n", classificationReport)

Validation Accuracy:  0.9225864390019015
Validation AUC:  0.9207042909297548
Confusion Matrix: 
 [[   8311    1843     158]
 [    291 2105442   17011]
 [    197  161180   39525]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.94      0.81      0.87     10312
           1       0.93      0.99      0.96   2122744
           2       0.70      0.20      0.31    200902

    accuracy                           0.92   2333958
   macro avg       0.86      0.66      0.71   2333958
weighted avg       0.91      0.92      0.90   2333958



Test on Test Data

In [30]:
yTestPredProbability = model.predict(xTest)  # Shape: [n_samples, n_classes]

# Convert probabilities to predicted class labels
yTestPred = np.argmax(yTestPredProbability, axis=1)  # Shape: [n_samples]

# Accuracy
testAccuracy = accuracy_score(yTest, yTestPred)
print("Test Accuracy: ", testAccuracy)

# AUC (for multi-class)
testAUC = roc_auc_score(yTest, yTestPredProbability, multi_class='ovr', average='macro')
print("Test AUC: ", testAUC)

# Confusion Matrix
testConfusionMatrix = confusion_matrix(yTest, yTestPred)
print("Test Confusion Matrix: \n", testConfusionMatrix)

# Classification Report
testClassificationReport = classification_report(yTest, yTestPred)
print("Test Classification Report: \n", testClassificationReport)

Test Accuracy:  0.9225915473164245
Test AUC:  0.9208545933576984
Test Confusion Matrix: 
 [[   8371    1841     143]
 [    270 2105266   16911]
 [    188  161315   39652]]
Test Classification Report: 
               precision    recall  f1-score   support

           0       0.95      0.81      0.87     10355
           1       0.93      0.99      0.96   2122447
           2       0.70      0.20      0.31    201155

    accuracy                           0.92   2333957
   macro avg       0.86      0.67      0.71   2333957
weighted avg       0.91      0.92      0.90   2333957



Feature Importance! 

In [14]:
import plotly.express as px
import pandas as pd

# Get Feature Importance
importance = model.feature_importance(importance_type='gain')
feature_names = X.columns

# Create DataFrame
importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importance})

# Sort by Importance (Descending)
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Plot using Plotly
fig = px.bar(
    importance_df,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Feature Importance',
    labels={'Importance': 'Gain'},
    height=600
)

# Show interactive plot
fig.show()

ON TOP one kinda looks like shit 
im plotting top 20 

In [15]:
import plotly.express as px
import pandas as pd
import numpy as np

# Get Feature Importance
importance = model.feature_importance(importance_type='gain')
feature_names = X.columns

# Get indices of top 20 most important features
top_n = 20
sorted_indices = np.argsort(importance)[-top_n:]  # Get indices of top 20 features

# Sort features and importance scores by importance
top_feature_names = np.array(feature_names)[sorted_indices]
top_importance_scores = np.array(importance)[sorted_indices]

# Create DataFrame
importance_df = pd.DataFrame({
    'Feature': top_feature_names,
    'Importance': top_importance_scores
})

# Sort by Importance (Descending)
importance_df = importance_df.sort_values(by='Importance', ascending=True)

# Plot using Plotly
fig = px.bar(
    importance_df,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Top 20 Feature Importance',
    labels={'Importance': 'Gain'},
    height=600
)

# Customize layout
fig.update_traces(marker_color='skyblue')
fig.update_layout(xaxis_gridcolor='lightgray', xaxis_gridwidth=0.5)

# Show interactive plot
fig.show()

## Predicting

In [ ]:
# Predicting on the dataset
X = df.drop(columns=["Departure_Status"])
y = df["Departure_Status"].astype('category').cat.codes
catFeat = X.select_dtypes(include='category').columns.tolist()

# Ensure categorical features are treated correctly
for col in catFeat:
    X[col] = X[col].astype('category')

# Make predictions
y_pred = model.predict(X)

# Convert probabilities to class labels
y_pred_labels = y_pred.argmax(axis=1)  # Takes the index of the max probability class

# Add predictions to the dataframe
df["Predicted_Departure_Status"] = y_pred_labels

In [ ]:
# Count occurrences of each unique value in the "Predicted_Departure_Status" column
unique_value_counts = df["Predicted_Departure_Status"].value_counts()

# Display the result
print(unique_value_counts)
## 1 Departure Delayed
## 2 Departure On Time
## 3 Cancelled


Predicted_Departure_Status
1    11479658
2      147484
0       42645
Name: count, dtype: int64


In [ ]:
unique_value_counts = df["Departure_Status"].value_counts()
print(unique_value_counts)


Departure_Status
Departure Delayed    10611222
Departure On Time     1006930
Cancelled               51635
Name: count, dtype: int64


In [ ]:
df = pd.read_parquet("../data.parquet")
df["Predicted_Departure_Status"] = y_pred_labels
output_file_path = "updated_file.parquet"  
df.to_parquet(output_file_path, index=False)

In [ ]:
import pandas as pd
df=pd.read_parquet("updated_file.parquet")
df.columns
print(len(df.columns))

68


In [ ]:
df=pd.read_parquet("../data.parquet")
df.columns
print(len(df.columns))

67
